apiVersion: v1
kind: Service
metadata:
  name: guestbook-service
  labels:
    name: guestbook-service
    app: demo-guestbook-app
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    name: guestbook-app-pod
    app: demo-guestbook-app