apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: demo-guestbook-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-master
      app: demo-guestbook-app
  template:
    metadata:
      name: redis-master
      labels:
        name: redis-master
        app: demo-guestbook-app
    spec:
      containers:
        - name: redis-master
          image: redis
          ports:
            - containerPort: 6379
